/* AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
 * Generated by tools/gen_stubs.py
 */

#include <stdint.h>
typedef uint8_t u8;
typedef int16_t s16;
typedef uint16_t u16;
typedef uint32_t u32;

/*
 * Data stubs: temporary placeholders for assets (SFX/MUS/ROM tables).
 * Replace with real ROM mapping / asset loading later.
 */

/* gUnk_0800275C â€” collision direction masks (u16[32]) from ROM 0x0800275C */
const u8 gUnk_0800275C[64] = {
    0x06, 0x00, 0x06, 0x60, 0x06, 0x60, 0x06, 0x60, 0x06, 0x60, 0x06, 0x60, 0x06, 0x60, 0x06, 0x60,
    0x00, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60, 0x60,
    0x60, 0x00, 0x60, 0x06, 0x60, 0x06, 0x60, 0x06, 0x60, 0x06, 0x60, 0x06, 0x60, 0x06, 0x60, 0x06,
    0x00, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06,
};
/* gUnk_080046A4 and gUnk_080047F6 now provided by src/data/data_080046A4.c */
/* BG tilemap DMA size table (u16[4]): sizes for screen sizes 0-3 */
const u16 gUnk_080B2CD8[4] = { 0x0800, 0x1000, 0x1000, 0x2000 };
/* Direction offset table (s16 xy pairs, indexed by animationState & 6).
   Used by UpdatePlayerCollision to check the tile AHEAD of the player. */
const s16 gUnk_080B4468[8] = {
    0,   -15, /* North: 15px above */
    12,  -3,  /* East:  12px right, 3px above */
    0,   9,   /* South: 9px below */
    -12, -3,  /* West:  12px left, 3px above */
};
/* Direction offset table for door transition position calculation. */
const s16 gUnk_080B4478[8] = {
    0,   -15, /* North */
    12,  -3,  /* East */
    0,   12,  /* South */
    -12, -3,  /* West */
};
/* Tile position offset per direction (s16[4], indexed by direction >> 3).
   -64 = one row up, +1 = one col right, +64 = one row down, -1 = one col left. */
const s16 gUnk_080B4488[4] = { -64, 1, 64, -1 };
/* Direction offset table for border/scroll checks (s16 xy pairs). */
const s16 gUnk_080B4490[8] = {
    0,  -9, /* North */
    6,  0,  /* East */
    0,  3,  /* South */
    -6, 0,  /* West */
};
/* Collision direction masks (u16[4], indexed by animationState >> 1). */
const u16 gUnk_080B44A0[4] = { 0x000E, 0xE000, 0x00E0, 0x0E00 };
/* Direction offset table (s16 xy pairs) for climbing/ladder checks. */
const s16 gUnk_080B44A8[8] = {
    0,   -12, /* North */
    12,  0,   /* East */
    0,   12,  /* South */
    -12, 0,   /* West */
};
/* gUnk_080B44B8: function pointer table for tile entity condition checks.
   On GBA these are sub_0801AE30 (always TRUE) and sub_0801AE34 (scroll_flags check).
   Using non-zero values so the != 0 check passes. */
const u32 gUnk_080B44B8[2] = { 1, 1 };
/* gUnk_080B44C0: tile entity table for layer 1 â€” empty (just terminator 0xFFFF) */
const u16 gUnk_080B44C0[] = { 0xFFFF };
/* gUnk_080B44C2: tile entity table for layer 2 â€” 1 entry + terminator
   Data { tileType=0x75, kind=9, id=0x25, type=0, type2=0, unk_a=1 } */
const u16 gUnk_080B44C2[] = { 0x0075, 0x0009, 0x0025, 0x0000, 0x0000, 0x0001, 0xFFFF };
u8 gUnk_080C9044[8] = { 0 };
/* Hitbox data (gUnk_080FD178 through gUnk_080FD588) is now provided by src/data/hitbox.c */
/* Font/text data â€” loaded from ROM by Port_LoadRom */
void* gTextVariableSources[5];
u8 gUnk_08109244[4] __attribute__((aligned(4)));
void* gUnk_08109248[9];
u8 gUnk_0810926C[64] __attribute__((aligned(4)));
void* gUnk_081092AC[10];
u8 gUnk_081092D4[346] __attribute__((aligned(4)));
u8 gUnk_0810942E[160] __attribute__((aligned(4)));
u8 gUnk_081094CE[1378] __attribute__((aligned(4)));
void* gUnk_0810B6EC[21]; /* SpriteLoadData* pointer table â€” resolved at init */
const u32 gTownspersonSpriteLoadDataCount = sizeof(gUnk_0810B6EC) / sizeof(gUnk_0810B6EC[0]);
/* gUnk_0810B774 and gUnk_0810B77C: function pointer tables, defined in port_linked_stubs.c */
/* gUnk_08128A38: defined in figurineMenuData.c (struct with func ptrs) */
/* gUnk_08128AD8: defined in figurineMenuData.c */
/* gUnk_08128D14, gUnk_08128D24, gUnk_08128D30: func ptr tables, defined in port_linked_stubs.c */
/* gUnk_08128D58: func ptr table, defined in port_linked_stubs.c */
/* gUnk_08128DB0: func ptr table, defined in port_linked_stubs.c */
/* gUnk_08128DCC: func ptr table, defined in port_linked_stubs.c */
/* gUnk_08128E78: func ptr table, defined in port_linked_stubs.c */
/* gUnk_08128F1C: func ptr table, defined in port_linked_stubs.c */
/* gUnk_0812901C -- defined in port_stubs.c as proper function pointer table */
/* gUnk_08133368 (OBJ palettes) now provided by src/data/objPalettes.c */
/* gUnk_08134FBC, gUnk_08135048, gUnk_08135190, gUnk_0813A76C now provided by src/data/transitions.c */
/* gUnk_0813AB58..gUnk_0813ADEC (screen transitions) now provided by src/data/screenTransitions.c */
const u8 sfx100[1] = { 0 };
const u8 sfx101[1] = { 0 };
const u8 sfx102[1] = { 0 };
const u8 sfx103[1] = { 0 };
const u8 sfx104[1] = { 0 };
const u8 sfx105[1] = { 0 };
const u8 sfx106[1] = { 0 };
const u8 sfx107[1] = { 0 };
const u8 sfx108[1] = { 0 };
const u8 sfx109[1] = { 0 };
const u8 sfx10A[1] = { 0 };
const u8 sfx10B[1] = { 0 };
const u8 sfx10D[1] = { 0 };
const u8 sfx10E[1] = { 0 };
const u8 sfx10F[1] = { 0 };
const u8 sfx110[1] = { 0 };
const u8 sfx111[1] = { 0 };
const u8 sfx112[1] = { 0 };
const u8 sfx113[1] = { 0 };
const u8 sfx114[1] = { 0 };
const u8 sfx115[1] = { 0 };
const u8 sfx116[1] = { 0 };
const u8 sfx117[1] = { 0 };
const u8 sfx11C[1] = { 0 };
const u8 sfx11D[1] = { 0 };
const u8 sfx122[1] = { 0 };
const u8 sfx123[1] = { 0 };
const u8 sfx124[1] = { 0 };
const u8 sfx125[1] = { 0 };
const u8 sfx126[1] = { 0 };
const u8 sfx12A[1] = { 0 };
const u8 sfx12B[1] = { 0 };
const u8 sfx12C[1] = { 0 };
const u8 sfx12D[1] = { 0 };
const u8 sfx12E[1] = { 0 };
const u8 sfx12F[1] = { 0 };
const u8 sfx130[1] = { 0 };
const u8 sfx131[1] = { 0 };
const u8 sfx132[1] = { 0 };
const u8 sfx133[1] = { 0 };
const u8 sfx134[1] = { 0 };
const u8 sfx135[1] = { 0 };
const u8 sfx136[1] = { 0 };
const u8 sfx137[1] = { 0 };
const u8 sfx138[1] = { 0 };
const u8 sfx139[1] = { 0 };
const u8 sfx13A[1] = { 0 };
const u8 sfx13B[1] = { 0 };
const u8 sfx13C[1] = { 0 };
const u8 sfx140[1] = { 0 };
const u8 sfx143[1] = { 0 };
const u8 sfx144[1] = { 0 };
const u8 sfx145[1] = { 0 };
const u8 sfx146[1] = { 0 };
const u8 sfx147[1] = { 0 };
const u8 sfx148[1] = { 0 };
const u8 sfx149[1] = { 0 };
const u8 sfx14A[1] = { 0 };
const u8 sfx14B[1] = { 0 };
const u8 sfx14C[1] = { 0 };
const u8 sfx14D[1] = { 0 };
const u8 sfx14E[1] = { 0 };
const u8 sfx14F[1] = { 0 };
const u8 sfx150[1] = { 0 };
const u8 sfx151[1] = { 0 };
const u8 sfx153[1] = { 0 };
const u8 sfx154[1] = { 0 };
const u8 sfx155[1] = { 0 };
const u8 sfx156[1] = { 0 };
const u8 sfx157[1] = { 0 };
const u8 sfx158[1] = { 0 };
const u8 sfx159[1] = { 0 };
const u8 sfx15A[1] = { 0 };
const u8 sfx15B[1] = { 0 };
const u8 sfx15C[1] = { 0 };
const u8 sfx15D[1] = { 0 };
const u8 sfx15E[1] = { 0 };
const u8 sfx15F[1] = { 0 };
const u8 sfx160[1] = { 0 };
const u8 sfx161[1] = { 0 };
const u8 sfx162[1] = { 0 };
const u8 sfx164[1] = { 0 };
const u8 sfx165[1] = { 0 };
const u8 sfx166[1] = { 0 };
const u8 sfx167[1] = { 0 };
const u8 sfx168[1] = { 0 };
const u8 sfx169[1] = { 0 };
const u8 sfx16A[1] = { 0 };
const u8 sfx16C[1] = { 0 };
const u8 sfx16D[1] = { 0 };
const u8 sfx16E[1] = { 0 };
const u8 sfx171[1] = { 0 };
const u8 sfx172[1] = { 0 };
const u8 sfx174[1] = { 0 };
const u8 sfx175[1] = { 0 };
const u8 sfx176[1] = { 0 };
const u8 sfx177[1] = { 0 };
const u8 sfx178[1] = { 0 };
const u8 sfx179[1] = { 0 };
const u8 sfx17A[1] = { 0 };
const u8 sfx180[1] = { 0 };
const u8 sfx181[1] = { 0 };
const u8 sfx182[1] = { 0 };
const u8 sfx183[1] = { 0 };
const u8 sfx184[1] = { 0 };
const u8 sfx185[1] = { 0 };
const u8 sfx186[1] = { 0 };
const u8 sfx189[1] = { 0 };
const u8 sfx18A[1] = { 0 };
const u8 sfx18B[1] = { 0 };
const u8 sfx18C[1] = { 0 };
const u8 sfx18D[1] = { 0 };
const u8 sfx18E[1] = { 0 };
const u8 sfx18F[1] = { 0 };
const u8 sfx190[1] = { 0 };
const u8 sfx191[1] = { 0 };
const u8 sfx192[1] = { 0 };
const u8 sfx193[1] = { 0 };
const u8 sfx194[1] = { 0 };
const u8 sfx195[1] = { 0 };
const u8 sfx196[1] = { 0 };
const u8 sfx197[1] = { 0 };
const u8 sfx198[1] = { 0 };
const u8 sfx199[1] = { 0 };
const u8 sfx19A[1] = { 0 };
const u8 sfx19B[1] = { 0 };
const u8 sfx19C[1] = { 0 };
const u8 sfx19D[1] = { 0 };
const u8 sfx19E[1] = { 0 };
const u8 sfx19F[1] = { 0 };
const u8 sfx1A0[1] = { 0 };
const u8 sfx1A1[1] = { 0 };
const u8 sfx1A2[1] = { 0 };
const u8 sfx1A3[1] = { 0 };
const u8 sfx1A4[1] = { 0 };
const u8 sfx1A5[1] = { 0 };
const u8 sfx1A6[1] = { 0 };
const u8 sfx1A7[1] = { 0 };
const u8 sfx1A8[1] = { 0 };
const u8 sfx1A9[1] = { 0 };
const u8 sfx1AA[1] = { 0 };
const u8 sfx1AB[1] = { 0 };
const u8 sfx1AC[1] = { 0 };
const u8 sfx1AD[1] = { 0 };
const u8 sfx1AE[1] = { 0 };
const u8 sfx1AF[1] = { 0 };
const u8 sfx1B0[1] = { 0 };
const u8 sfx1B4[1] = { 0 };
const u8 sfx1B5[1] = { 0 };
const u8 sfx1B6[1] = { 0 };
const u8 sfx1BC[1] = { 0 };
const u8 sfx1BD[1] = { 0 };
const u8 sfx1BE[1] = { 0 };
const u8 sfx1BF[1] = { 0 };
const u8 sfx1C0[1] = { 0 };
const u8 sfx1C1[1] = { 0 };
const u8 sfx1C2[1] = { 0 };
const u8 sfx1C3[1] = { 0 };
const u8 sfx1C4[1] = { 0 };
const u8 sfx1C5[1] = { 0 };
const u8 sfx1C6[1] = { 0 };
const u8 sfx1C7[1] = { 0 };
const u8 sfx1C8[1] = { 0 };
const u8 sfx1C9[1] = { 0 };
const u8 sfx1CA[1] = { 0 };
const u8 sfx1CB[1] = { 0 };
const u8 sfx1CC[1] = { 0 };
const u8 sfx1D0[1] = { 0 };
const u8 sfx1D2[1] = { 0 };
const u8 sfx1D3[1] = { 0 };
const u8 sfx1D4[1] = { 0 };
const u8 sfx1D5[1] = { 0 };
const u8 sfx1DB[1] = { 0 };
const u8 sfx1DC[1] = { 0 };
const u8 sfx1DD[1] = { 0 };
const u8 sfx1DE[1] = { 0 };
const u8 sfx1DF[1] = { 0 };
const u8 sfx1E0[1] = { 0 };
const u8 sfx1E1[1] = { 0 };
const u8 sfx1E2[1] = { 0 };
const u8 sfx1E3[1] = { 0 };
const u8 sfx1E4[1] = { 0 };
const u8 sfx1E5[1] = { 0 };
const u8 sfx1E6[1] = { 0 };
const u8 sfx1E7[1] = { 0 };
const u8 sfx1E8[1] = { 0 };
const u8 sfx1E9[1] = { 0 };
const u8 sfx1EA[1] = { 0 };
const u8 sfx1EB[1] = { 0 };
const u8 sfx1EC[1] = { 0 };
const u8 sfx1ED[1] = { 0 };
const u8 sfx1EE[1] = { 0 };
const u8 sfx1EF[1] = { 0 };
const u8 sfx1F0[1] = { 0 };
const u8 sfx1F1[1] = { 0 };
const u8 sfx1F2[1] = { 0 };
const u8 sfx1F3[1] = { 0 };
const u8 sfx1F4[1] = { 0 };
const u8 sfx1F5[1] = { 0 };
const u8 sfx1F6[1] = { 0 };
const u8 sfx1F7[1] = { 0 };
const u8 sfx1F8[1] = { 0 };
const u8 sfx1F9[1] = { 0 };
const u8 sfx1FA[1] = { 0 };
const u8 sfx1FB[1] = { 0 };
const u8 sfx1FC[1] = { 0 };
const u8 sfx1FD[1] = { 0 };
const u8 sfx1FE[1] = { 0 };
const u8 sfx1FF[1] = { 0 };
const u8 sfx200[1] = { 0 };
const u8 sfx201[1] = { 0 };
const u8 sfx202[1] = { 0 };
const u8 sfx203[1] = { 0 };
const u8 sfx204[1] = { 0 };
const u8 sfx205[1] = { 0 };
const u8 sfx206[1] = { 0 };
const u8 sfx207[1] = { 0 };
const u8 sfx208[1] = { 0 };
const u8 sfx209[1] = { 0 };
const u8 sfx20A[1] = { 0 };
const u8 sfx20B[1] = { 0 };
const u8 sfx20C[1] = { 0 };
const u8 sfx20D[1] = { 0 };
const u8 sfx20E[1] = { 0 };
const u8 sfx20F[1] = { 0 };
const u8 sfx210[1] = { 0 };
const u8 sfx211[1] = { 0 };
const u8 sfx212[1] = { 0 };
const u8 sfx213[1] = { 0 };
const u8 sfx214[1] = { 0 };
const u8 sfx215[1] = { 0 };
const u8 sfx216[1] = { 0 };
const u8 sfx217[1] = { 0 };
const u8 sfx218[1] = { 0 };
const u8 sfx219[1] = { 0 };
const u8 sfx21A[1] = { 0 };
const u8 sfx21B[1] = { 0 };
const u8 sfx21C[1] = { 0 };
const u8 sfx21D[1] = { 0 };
const u8 sfx21E[1] = { 0 };
const u8 sfx21F[1] = { 0 };
const u8 sfx220[1] = { 0 };
const u8 sfx221[1] = { 0 };
const u8 sfx6B[1] = { 0 };
const u8 sfx7E[1] = { 0 };
const u8 sfx80[1] = { 0 };
const u8 sfx81[1] = { 0 };
const u8 sfx82[1] = { 0 };
const u8 sfx86[1] = { 0 };
const u8 sfx88[1] = { 0 };
const u8 sfx9B[1] = { 0 };
const u8 sfx9C[1] = { 0 };
const u8 sfx9D[1] = { 0 };
const u8 sfx9E[1] = { 0 };
const u8 sfx9F[1] = { 0 };
const u8 sfxA0[1] = { 0 };
const u8 sfxA8[1] = { 0 };
const u8 sfxA9[1] = { 0 };
const u8 sfxAA[1] = { 0 };
const u8 sfxAC[1] = { 0 };
const u8 sfxAE[1] = { 0 };
const u8 sfxAF[1] = { 0 };
const u8 sfxApparate[1] = { 0 };
const u8 sfxB0[1] = { 0 };
const u8 sfxB5[1] = { 0 };
const u8 sfxB6[1] = { 0 };
const u8 sfxB7[1] = { 0 };
const u8 sfxB8[1] = { 0 };
const u8 sfxB9[1] = { 0 };
const u8 sfxBA[1] = { 0 };
const u8 sfxBB[1] = { 0 };
const u8 sfxBC[1] = { 0 };
const u8 sfxBD[1] = { 0 };
const u8 sfxBE[1] = { 0 };
const u8 sfxBF[1] = { 0 };
const u8 sfxBarrelEnter[1] = { 0 };
const u8 sfxBarrelRelease[1] = { 0 };
const u8 sfxBarrelRoll[1] = { 0 };
const u8 sfxBarrelRollStop[1] = { 0 };
const u8 sfxBeep[1] = { 0 };
const u8 sfxBossDie[1] = { 0 };
const u8 sfxBossExplode[1] = { 0 };
const u8 sfxBossHit[1] = { 0 };
const u8 sfxButtonDepress[1] = { 0 };
const u8 sfxButtonPress[1] = { 0 };
const u8 sfxC0[1] = { 0 };
const u8 sfxC1[1] = { 0 };
const u8 sfxC2[1] = { 0 };
const u8 sfxC3[1] = { 0 };
const u8 sfxC4[1] = { 0 };
const u8 sfxC5[1] = { 0 };
const u8 sfxC6[1] = { 0 };
const u8 sfxC7[1] = { 0 };
const u8 sfxC8[1] = { 0 };
const u8 sfxC9[1] = { 0 };
const u8 sfxCA[1] = { 0 };
const u8 sfxCB[1] = { 0 };
const u8 sfxCF[1] = { 0 };
const u8 sfxChargingUp[1] = { 0 };
const u8 sfxChestOpen[1] = { 0 };
const u8 sfxCuccoMinigameBell[1] = { 0 };
const u8 sfxD0[1] = { 0 };
const u8 sfxD9[1] = { 0 };
const u8 sfxDA[1] = { 0 };
const u8 sfxE3[1] = { 0 };
const u8 sfxE4[1] = { 0 };
const u8 sfxEA[1] = { 0 };
const u8 sfxEB[1] = { 0 };
const u8 sfxEC[1] = { 0 };
const u8 sfxED[1] = { 0 };
const u8 sfxEE[1] = { 0 };
const u8 sfxEF[1] = { 0 };
const u8 sfxElementCharge[1] = { 0 };
const u8 sfxElementFloat[1] = { 0 };
const u8 sfxElementInfuse[1] = { 0 };
const u8 sfxElementPlace[1] = { 0 };
const u8 sfxEmArmosOn[1] = { 0 };
const u8 sfxEmDekuscrubHit[1] = { 0 };
const u8 sfxEmMoblinSpear[1] = { 0 };
const u8 sfxEvaporate[1] = { 0 };
const u8 sfxEzloUi[1] = { 0 };
const u8 sfxF0[1] = { 0 };
const u8 sfxF1[1] = { 0 };
const u8 sfxF2[1] = { 0 };
const u8 sfxF3[1] = { 0 };
const u8 sfxF5[1] = { 0 };
const u8 sfxF8[1] = { 0 };
const u8 sfxFA[1] = { 0 };
const u8 sfxFB[1] = { 0 };
const u8 sfxFC[1] = { 0 };
const u8 sfxFF[1] = { 0 };
const u8 sfxFallHole[1] = { 0 };
const u8 sfxHammer1[1] = { 0 };
const u8 sfxHammer2[1] = { 0 };
const u8 sfxHammer3[1] = { 0 };
const u8 sfxHammer4[1] = { 0 };
const u8 sfxHammer5[1] = { 0 };
const u8 sfxHammer6[1] = { 0 };
const u8 sfxHeartBounce[1] = { 0 };
const u8 sfxHeartContainerSpawn[1] = { 0 };
const u8 sfxHeartGet[1] = { 0 };
const u8 sfxHit[1] = { 0 };
const u8 sfxIceBlockMelt[1] = { 0 };
const u8 sfxIceBlockSlide[1] = { 0 };
const u8 sfxIceBlockStop[1] = { 0 };
const u8 sfxItemBombExplode[1] = { 0 };
const u8 sfxItemGlovesKnockback[1] = { 0 };
const u8 sfxItemLanternOff[1] = { 0 };
const u8 sfxItemLanternOn[1] = { 0 };
const u8 sfxItemShieldBounce[1] = { 0 };
const u8 sfxItemSwordBeam[1] = { 0 };
const u8 sfxItemSwordCharge[1] = { 0 };
const u8 sfxItemSwordChargeFinish[1] = { 0 };
const u8 sfxKeyAppear[1] = { 0 };
const u8 sfxLavaTitleFlip[1] = { 0 };
const u8 sfxLavaTitleLand[1] = { 0 };
const u8 sfxLavaTitleSink[1] = { 0 };
const u8 sfxLavaTitleStep[1] = { 0 };
const u8 sfxLavaTitleWobble[1] = { 0 };
const u8 sfxLowHealth[1] = { 0 };
const u8 sfxMenuCancel[1] = { 0 };
const u8 sfxMenuError[1] = { 0 };
const u8 sfxMetalClink[1] = { 0 };
const u8 sfxMinish1[1] = { 0 };
const u8 sfxMinish2[1] = { 0 };
const u8 sfxMinish3[1] = { 0 };
const u8 sfxMinish4[1] = { 0 };
const u8 sfxNearPortal[1] = { 0 };
const u8 sfxNone[1] = { 0 };
const u8 sfxPlyDie[1] = { 0 };
const u8 sfxPlyGrow[1] = { 0 };
const u8 sfxPlyJump[1] = { 0 };
const u8 sfxPlyLand[1] = { 0 };
const u8 sfxPlyLift[1] = { 0 };
const u8 sfxPlyShrinking[1] = { 0 };
const u8 sfxPlyVo1[1] = { 0 };
const u8 sfxPlyVo2[1] = { 0 };
const u8 sfxPlyVo3[1] = { 0 };
const u8 sfxPlyVo4[1] = { 0 };
const u8 sfxPlyVo5[1] = { 0 };
const u8 sfxPlyVo6[1] = { 0 };
const u8 sfxPlyVo7[1] = { 0 };
const u8 sfxPressurePlate[1] = { 0 };
const u8 sfxRemSleep[1] = { 0 };
const u8 sfxRupeeBounce[1] = { 0 };
const u8 sfxRupeeGet[1] = { 0 };
const u8 sfxSecret[1] = { 0 };
const u8 sfxSecretBig[1] = { 0 };
const u8 sfxSparkles[1] = { 0 };
const u8 sfxSpiritsRelease[1] = { 0 };
const u8 sfxStairs[1] = { 0 };
const u8 sfxStairsAscend[1] = { 0 };
const u8 sfxStairsDescend[1] = { 0 };
const u8 sfxSummon[1] = { 0 };
const u8 sfxTaskComplete[1] = { 0 };
const u8 sfxTeleporter[1] = { 0 };
const u8 sfxTextboxChoice[1] = { 0 };
const u8 sfxTextboxClose[1] = { 0 };
const u8 sfxTextboxNext[1] = { 0 };
const u8 sfxTextboxOpen[1] = { 0 };
const u8 sfxTextboxSelect[1] = { 0 };
const u8 sfxTextboxSwap[1] = { 0 };
const u8 sfxThudHeavy[1] = { 0 };
const u8 sfxToggleDiving[1] = { 0 };
const u8 sfxVoBeedle[1] = { 0 };
const u8 sfxVoCat[1] = { 0 };
const u8 sfxVoCheep[1] = { 0 };
const u8 sfxVoCow[1] = { 0 };
const u8 sfxVoCucco1[1] = { 0 };
const u8 sfxVoCucco2[1] = { 0 };
const u8 sfxVoCucco3[1] = { 0 };
const u8 sfxVoCucco4[1] = { 0 };
const u8 sfxVoCucco5[1] = { 0 };
const u8 sfxVoCuccoCall[1] = { 0 };
const u8 sfxVoDog[1] = { 0 };
const u8 sfxVoEpona[1] = { 0 };
const u8 sfxVoEzlo1[1] = { 0 };
const u8 sfxVoEzlo2[1] = { 0 };
const u8 sfxVoEzlo3[1] = { 0 };
const u8 sfxVoEzlo4[1] = { 0 };
const u8 sfxVoEzlo5[1] = { 0 };
const u8 sfxVoEzlo6[1] = { 0 };
const u8 sfxVoEzlo7[1] = { 0 };
const u8 sfxVoGoron1[1] = { 0 };
const u8 sfxVoGoron2[1] = { 0 };
const u8 sfxVoGoron3[1] = { 0 };
const u8 sfxVoGoron4[1] = { 0 };
const u8 sfxVoKing1[1] = { 0 };
const u8 sfxVoKing2[1] = { 0 };
const u8 sfxVoKing3[1] = { 0 };
const u8 sfxVoKing4[1] = { 0 };
const u8 sfxVoKing5[1] = { 0 };
const u8 sfxVoSturgeon[1] = { 0 };
const u8 sfxVoTingle1[1] = { 0 };
const u8 sfxVoTingle2[1] = { 0 };
const u8 sfxVoZelda1[1] = { 0 };
const u8 sfxVoZelda2[1] = { 0 };
const u8 sfxVoZelda3[1] = { 0 };
const u8 sfxVoZelda4[1] = { 0 };
const u8 sfxVoZelda5[1] = { 0 };
const u8 sfxVoZelda6[1] = { 0 };
const u8 sfxVoZelda7[1] = { 0 };
const u8 sfxWaterSplash[1] = { 0 };
const u8 sfxWaterWalk[1] = { 0 };
const u8 sfxWind1[1] = { 0 };
const u8 sfxWind2[1] = { 0 };
const u8 sfxWind3[1] = { 0 };
/* ---- ROM data stub initialization ---- */
#include <stdio.h>
#include <string.h>
extern u8* gRomData;
extern u32 gRomSize;

#define PORT_DATA_STUB_SIZE 1024

void Port_InitDataStubs(void) {
    if (!gRomData || gRomSize == 0) {
        fprintf(stderr, "Port_InitDataStubs: ROM not loaded yet!\n");
        return;
    }
    u32 count = 0;
    /* gUnk_080046A4 and gUnk_080047F6 — now provided by src/data/data_080046A4.c */
    /* Hitbox data (gUnk_080FD178 through gUnk_080FD588) now provided by src/data/hitbox.c - no ROM loading needed */
    /* gUnk_0810B6EC @ 0x0810B6EC â€” SpriteLoadData* pointer table, resolve GBA addrs */
    {
        u32 off = 0x10B6ECu;
        for (u32 i = 0; i < gTownspersonSpriteLoadDataCount; i++) {
            u32 gba_addr;
            memcpy(&gba_addr, &gRomData[off + i * 4], 4);
            if (gba_addr >= 0x08000000u && gba_addr < 0x08000000u + gRomSize)
                gUnk_0810B6EC[i] = &gRomData[gba_addr - 0x08000000u];
            else
                gUnk_0810B6EC[i] = NULL;
        }
        count++;
    }
    /* gUnk_0810B774 and gUnk_0810B77C: function pointer tables, defined natively in port_linked_stubs.c â€” skip ROM
     * loading */
    /* gUnk_08128A38 and gUnk_08128AD8: defined in figurineMenuData.c â€” skip ROM loading */
    /* gUnk_08128D14, D24, D30: func ptr tables â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08128D58: func ptr table â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08128DB0: func ptr table â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08128DCC: func ptr table â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08128E78: func ptr table â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08128F1C: func ptr table â€” defined in port_linked_stubs.c, skip ROM loading */
    /* gUnk_08134FBC..gUnk_0813ADEC (transitions + screen transitions) now provided by src/data/ */
    /* gCollisionMtx — populate the full buffer from ROM.
     * collision.c declares it as `extern ColSettings gCollisionMtx[173*34]`
     * (each ColSettings = 12 bytes).  On GBA, reads go well beyond the 1210
     * bytes at 0x080B7B74 into adjacent ROM data.  Copy the full region so
     * collision handlers with hardcoded indices (like 0x11AA) also work. */
    {
        extern u8 gCollisionMtx[];
        u32 col_rom_off = 0x000B7B74u;
        u32 col_size = 173u * 34u * 12u; /* 70584 bytes */
        if (col_rom_off + col_size <= gRomSize) {
            memcpy(gCollisionMtx, &gRomData[col_rom_off], col_size);
        } else if (gRomSize > col_rom_off) {
            /* Partial copy: fill what we have, zero the rest */
            u32 avail = gRomSize - col_rom_off;
            memcpy(gCollisionMtx, &gRomData[col_rom_off], avail);
            memset(&gCollisionMtx[avail], 0, col_size - avail);
        }
        count++;
    }
    /* Per-room "additional entity list" data — most are dropped from
     * port_asset_index.c and the corresponding port_linked_stubs.c arrays
     * are zero. The C code at sub_StateChange_DeepwoodShrineBoss_Main does
     * `LoadRoomEntityList(&gUnk_additional_a_DeepwoodShrineBoss_Main)` to
     * spawn the heart container + warp after the boss dies, so without this
     * copy the rewards never appear (issue #12). USA addresses; EU/JP would
     * need different offsets. */
    {
        extern u8 gUnk_additional_a_DeepwoodShrineBoss_Main[];
        extern u8 gUnk_additional_8_MelarisMine_Main[];
        extern u8 gUnk_additional_9_MelarisMine_Main[];
        extern u8 gUnk_additional_8_DeepwoodShrine_StairsToB1[];
        extern u8 gUnk_additional_8_HouseInteriors1_Library1F[];
        extern u8 gUnk_additional_9_HouseInteriors1_Library1F[];
        extern u8 gUnk_additional_8_HyruleCastle_3[];
        extern u8 gUnk_additional_a_CaveOfFlamesBoss_Main[];
        extern u8 gUnk_additional_a_TempleOfDroplets_BigOcto[];
        extern u8 gUnk_additional_8_PalaceOfWinds_GyorgTornado[];
        extern u8 gUnk_additional_9_PalaceOfWinds_GyorgTornado[];
        extern u8 gUnk_additional_c_HouseInteriors2_Romio[];
        extern u8 gUnk_additional_9_HouseInteriors2_Percy[];
        extern u8 gUnk_additional_a_HouseInteriors2_Percy[];
        extern u8 gUnk_additional_8_HouseInteriors3_BorlovEntrance[];
        extern u8 gUnk_additional_9_HouseInteriors3_BorlovEntrance[];
        extern u8 gUnk_additional_a_HouseInteriors3_BorlovEntrance[];
        struct PerRoomEntityListInit { const char* name; u32 rom_offset; u32 size; u8* dest; };
        struct PerRoomEntityListInit entries[] = {
            { "gUnk_additional_a_DeepwoodShrineBoss_Main", 0xDF94Cu, 0x30u,
              gUnk_additional_a_DeepwoodShrineBoss_Main },
            /* Melari's Mines main room: state-change loads the additional_8
             * NPC list (2 minishes + Melari + 2 cutscene swords) and the
             * additional_9 helper-minish list. With zeroed stubs the
             * runtime parses 16-byte chunks of zeros as GROUND_ITEM kind=0
             * entities — visible as duplicate heart containers + green
             * warp tile in the room (#42), and Melari himself + his crew
             * never appear (#43). USA addresses; EU/JP would need different
             * offsets. */
            { "gUnk_additional_8_MelarisMine_Main", 0xDD214u, 0x60u,
              gUnk_additional_8_MelarisMine_Main },
            { "gUnk_additional_9_MelarisMine_Main", 0xDD274u, 0x20u,
              gUnk_additional_9_MelarisMine_Main },
            /* Per-room state-change additional entity lists. Each one is
             * loaded by sub_StateChange_<Room>() in roomInit.c via
             * LoadRoomEntityList() — which iterates EntityData records
             * until kind==0xFF. Zeroed stubs read kind=0 forever and
             * crash. Populating from ROM lets the lists terminate
             * correctly. Crashes covered: #64 (Temple of Droplets big-key
             * area, BigOcto state-change), #68 (Hyrule Town Romio's
             * "Purple House"), and others where the post-state-change
             * room never loaded its real entity list. USA addresses. */
            { "gUnk_additional_8_DeepwoodShrine_StairsToB1", 0xDE834u, 0x30u,
              gUnk_additional_8_DeepwoodShrine_StairsToB1 },
            { "gUnk_additional_8_HouseInteriors1_Library1F", 0xD66F4u, 0x20u,
              gUnk_additional_8_HouseInteriors1_Library1F },
            { "gUnk_additional_9_HouseInteriors1_Library1F", 0xD6734u, 0x50u,
              gUnk_additional_9_HouseInteriors1_Library1F },
            { "gUnk_additional_8_HyruleCastle_3", 0xD7690u, 0x40u,
              gUnk_additional_8_HyruleCastle_3 },
            { "gUnk_additional_a_CaveOfFlamesBoss_Main", 0xE1814u, 0x30u,
              gUnk_additional_a_CaveOfFlamesBoss_Main },
            { "gUnk_additional_a_TempleOfDroplets_BigOcto", 0xE49F4u, 0x30u,
              gUnk_additional_a_TempleOfDroplets_BigOcto },
            { "gUnk_additional_8_PalaceOfWinds_GyorgTornado", 0xE72E4u, 0x30u,
              gUnk_additional_8_PalaceOfWinds_GyorgTornado },
            { "gUnk_additional_9_PalaceOfWinds_GyorgTornado", 0xE7314u, 0x30u,
              gUnk_additional_9_PalaceOfWinds_GyorgTornado },
            { "gUnk_additional_c_HouseInteriors2_Romio", 0xF236Cu, 0x20u,
              gUnk_additional_c_HouseInteriors2_Romio },
            { "gUnk_additional_9_HouseInteriors2_Percy", 0xF2718u, 0x40u,
              gUnk_additional_9_HouseInteriors2_Percy },
            { "gUnk_additional_a_HouseInteriors2_Percy", 0xF2758u, 0x40u,
              gUnk_additional_a_HouseInteriors2_Percy },
            { "gUnk_additional_8_HouseInteriors3_BorlovEntrance", 0xF5F38u, 0x20u,
              gUnk_additional_8_HouseInteriors3_BorlovEntrance },
            { "gUnk_additional_9_HouseInteriors3_BorlovEntrance", 0xF5F58u, 0x20u,
              gUnk_additional_9_HouseInteriors3_BorlovEntrance },
            { "gUnk_additional_a_HouseInteriors3_BorlovEntrance", 0xF5F78u, 0x20u,
              gUnk_additional_a_HouseInteriors3_BorlovEntrance },
        };
        for (size_t i = 0; i < sizeof(entries)/sizeof(entries[0]); i++) {
            if (entries[i].rom_offset + entries[i].size <= gRomSize) {
                memcpy(entries[i].dest, &gRomData[entries[i].rom_offset], entries[i].size);
                count++;
            }
        }
    }
    fprintf(stderr, "Port_InitDataStubs: initialized %u data stubs from ROM.\n", count);
}
