/**
 * @file port_script_funcs.c
 * AUTO-GENERATED by tools/gen_script_funcs.py — DO NOT EDIT
 *
 * Lookup table mapping GBA function addresses to PC function pointers
 * for script Call/CallWithArg commands.
 */

#include "entity.h"
#include "script.h"
#include <stddef.h>

/* Forward declarations of all script-callable functions */
extern void AddInteractableCheckableObject();
extern void Anju_MakeInteractable();
extern void Beedle_ConfirmBuyItem();
extern void Beedle_GetObjectType();
extern void Beedle_IsBottleInInventory();
extern void BladeBrothers_CheckLastSwordMove();
extern void BladeBrothers_GetScroll();
extern void BladeBrothers_LearnSkill();
extern void BladeBrothers_ResetLastSwordMove();
extern void BladeBrothers_StartPlayerDemonstration();
extern void Brocco_MakeInteractable();
extern void Carpenter_MakeInteractable();
extern void CastleMaid_SetDialogFunc();
extern void CheckAnyKeyPressed();
extern void CheckEntityOnScreen();
extern void CheckInteractType();
extern void CheckLastSwordMove();
extern void CheckMessageEqual();
extern void CreateDust();
extern void CreatePlayerExclamationMark();
extern void CreatePlayerQuestionMark();
extern void CreateRepeatedSoundManager();
extern void CuccoMinigame_AdvanceLevel();
extern void CuccoMinigame_Cleanup();
extern void CuccoMinigame_Init();
extern void CuccoMinigame_Results();
extern void CuccoMinigame_TellObjective();
extern void CuccoMinigame_WinItem();
extern void CuccoMinigame_WinRupees();
extern void Dampe_MakeInteractable();
extern void DeleteAllEnemies();
extern void DeleteHitbox();
extern void DeleteNpcRem();
extern void DeleteRepeatedSoundManager();
extern void Din_MakeInteractable();
extern void DisablePauseMenu();
extern void DisablePauseMenuAndPutAwayItems();
extern void DisablePlayerSwimState();
extern void DisableRandomDrops();
extern void DoGravity();
extern void EnablePauseMenu();
extern void EnableRandomDrops();
extern void EquipItem();
extern void Farmers_MakeInteractable();
extern void Farmers_MarkEenieFuserDoner();
extern void Farore_MakeInteractable();
extern void FigurineDevice_LostOrFinishedMessage();
extern void FigurineDevice_NewFigurinesMessage();
extern void FigurineDevice_NoFigurinesLeftMessage();
extern void FigurineDevice_NothingNewToDrawMessage();
extern void FigurineDevice_TryAgainMessage();
extern void ForestMinish_MakeInteractable();
extern void GetConditionSet();
extern void GetRandomInt();
extern void GhostBrothers_MakeInteractable();
extern void GoronMerchant_TryToBuyKinstone();
extern void Goron_MakeInteractable();
extern void Gregal_MakeInteractable();
extern void GuardWithSpear_CheckSwordMoveSpin();
extern void GuardWithSpear_ResetLastSwordMove();
extern void GuardWithSpear_ResetLastSwordMoveIfNotInSwordState();
extern void HurdyGurdyMan_MakeInteractable();
extern void Kid_MakeInteractable();
extern void KingDaltus_MakeInteractable();
extern void LoadMenu();
extern void MakeCheckableObjectInteractable();
extern void MakeInteractableAsMinish();
extern void MakePedestalInteractable();
extern void Mama_MakeInteractable();
extern void MarkFuserDone();
extern void MayorHagen_MakeInteractable();
extern void Melari_MakeInteractable();
extern void MinisterPotho_MakeInteractable();
extern void MountainMinish_MakeInteractable();
extern void Mutoh_MakeInteractable();
extern void NPC4E_ChangeInteractableHitbox();
extern void NPC4E_DoScreenTransition();
extern void NPC4E_IsEveryPinwheelActivated();
extern void NPC4E_IsKinstoneFused();
extern void NPC4E_MakeFuserInteractable();
extern void NPC4E_RestoreEquippedItems();
extern void NPC4E_SaveEquippedItems();
extern void NPC4E_SetPinwheelFlag();
extern void Nayru_MakeInteractable();
extern void Percy_MakeInteractable();
extern void Pina_MakeInteractable();
extern void PlayerDropHeldObject();
extern void PlayerSetNormalAndCollide();
extern void Postman_MakeInteractable();
extern void PutItemAnySlot();
extern void ReadPlayerAnimationState();
extern void Rem_MakeInteractable();
extern void RemoveAllBakedGoods();
extern void ResetPlayerAnimationAndAction();
extern void ResetPlayerEventPriority();
extern void ResetPlayerFlag();
extern void ScriptCommand_BuyShopItem();
extern void ScriptCommand_CheckShopItemPrice();
extern void ScriptCommand_PlayerDropHeldObject();
extern void ScriptCommand_SaleItemConfirmMessage();
extern void ScriptCommand_SetMessageValue();
extern void SetCollisionLayer1();
extern void SetCollisionLayer2();
extern void SetEntityHeight();
extern void SetPlayerActionNormal();
extern void SetPlayerAnimation2();
extern void SetPlayerCollisionLayer1();
extern void SetPlayerEventPriority();
extern void SetPlayerFlag();
extern void SetPlayerIFrames();
extern void SetPlayerMacro();
extern void SetPlayerPos();
extern void SetPriorityHighest();
extern void SetPriorityMessage();
extern void SetPriorityPlayerEvent();
extern void SetSpriteOffset();
extern void Simon_CreateChest();
extern void SittingPersion_ShowDialogue();
extern void SittingPerson_MakeInteractable();
extern void Smith_ChangeInteractableHitbox();
extern void Smith_MakeInteractable();
extern void StartDarkNutTimer();
extern void Sturgeon_MakeInteractable();
extern void Teachers_MakeInteractable();
extern void TingleSiblings_MakeInteractable();
extern void TownMinish_MakeInteractable();
extern void Townsperson_MakeInteractable();
extern void UpdatePlayerSkills();
extern void Vaati_Apparate();
extern void Vaati_Evaporate();
extern void WaitForAnimDone();
extern void WaitForCameraTouchRoomBorder();
extern void WaitForPlayerAnim();
extern void WaitForPlayerIdle();
extern void WaitForPlayerMacro();
extern void WaitForPlayerNormal();
extern void WaitForPlayerNormalOrTalkEzlo();
extern void WindTribespeople_MakeInteractable();
extern void Windcrest_ChangeInteractableHitbox();
extern void Windcrest_Unlock();
extern void nullsub_527();
extern void script_ModBombs();
extern void sub_08046078();
extern void sub_0804BCDC();
extern void sub_0804BF38();
extern void sub_0804D7EC();
extern void sub_0804D810();
extern void sub_0804E864();
extern void sub_0804F6A8();
extern void sub_0804F6C8();
extern void sub_0804F6E8();
extern void sub_0804F724();
extern void sub_0804F760();
extern void sub_0804F79C();
extern void sub_0804F808();
extern void sub_0804F830();
extern void sub_0804F854();
extern void sub_0804F89C();
extern void sub_0804F8E0();
extern void sub_0804F928();
extern void sub_0804F944();
extern void sub_0804F960();
extern void sub_0804F994();
extern void sub_0804F9C8();
extern void sub_08053250();
extern void sub_08053634();
extern void sub_08053648();
extern void sub_0805367C();
extern void sub_0805368C();
extern void sub_080536A8();
extern void sub_080536B8();
extern void sub_08053B3C();
extern void sub_08053BE8();
extern void sub_08053C84();
extern void sub_08054968();
extern void sub_0806014C();
extern void sub_08060158();
extern void sub_08060208();
extern void sub_0806021C();
extern void sub_0806025C();
extern void sub_08060270();
extern void sub_080602BC();
extern void sub_08060318();
extern void sub_08060340();
extern void sub_08060700();
extern void sub_0806075C();
extern void sub_0806076C();
extern void sub_080608E4();
extern void sub_08061E90();
extern void sub_08061F94();
extern void sub_08061FB0();
extern void sub_08061FB8();
extern void sub_08061FD8();
extern void sub_08061FE4();
extern void sub_08061FF4();
extern void sub_0806200C();
extern void sub_08062048();
extern void sub_08062500();
extern void sub_0806265C();
extern void sub_08062698();
extern void sub_080626AC();
extern void sub_080626C0();
extern void sub_08062788();
extern void sub_080627E8();
extern void sub_08062948();
extern void sub_08062CBC();
extern void sub_08062D18();
extern void sub_08062E14();
extern void sub_08062EDC();
extern void sub_0806305C();
extern void sub_080630A4();
extern void sub_080636D8();
extern void sub_08063850();
extern void sub_08063874();
extern void sub_08063C14();
extern void sub_08063C2C();
extern void sub_08063C44();
extern void sub_08063C5C();
extern void sub_08063C74();
extern void sub_08063C90();
extern void sub_08064050();
extern void sub_0806407C();
extern void sub_08064180();
extern void sub_08064198();
extern void sub_080642B8();
extern void sub_080643D8();
extern void sub_08064428();
extern void sub_080646A4();
extern void sub_08064CD8();
extern void sub_08064D08();
extern void sub_08064D10();
extern void sub_08064F28();
extern void sub_08065370();
extern void sub_080654DC();
extern void sub_080654EC();
extern void sub_080654FC();
extern void sub_08065528();
extern void sub_08065780();
extern void sub_08065914();
extern void sub_08065CCC();
extern void sub_08065F64();
extern void sub_0806622C();
extern void sub_08066258();
extern void sub_0806673C();
extern void sub_08066904();
extern void sub_08066D04();
extern void sub_08066D14();
extern void sub_08066D4C();
extern void sub_08066E08();
extern void sub_08066E20();
extern void sub_08066E38();
extern void sub_08066E50();
extern void sub_08066E68();
extern void sub_08066E80();
extern void sub_08066F94();
extern void sub_08066FB8();
extern void sub_080670B4();
extern void sub_080670E4();
extern void sub_080672B0();
extern void sub_080672C8();
extern void sub_08067304();
extern void sub_08067534();
extern void sub_0806757C();
extern void sub_080675D4();
extern void sub_080676D8();
extern void sub_080676E0();
extern void sub_0806811C();
extern void sub_08068190();
extern void sub_080681D8();
extern void sub_08068910();
extern void sub_08068964();
extern void sub_08068BB4();
extern void sub_08068BD0();
extern void sub_08068C28();
extern void sub_08068C8C();
extern void sub_08068CA0();
extern void sub_08068CFC();
extern void sub_08068DB8();
extern void sub_08068DD0();
extern void sub_08068DE8();
extern void sub_08068E00();
extern void sub_08068E18();
extern void sub_08068E30();
extern void sub_08068E48();
extern void sub_08068E60();
extern void sub_08068E78();
extern void sub_08068F00();
extern void sub_08068F14();
extern void sub_08068F3C();
extern void sub_0806948C();
extern void sub_080694D8();
extern void sub_080694EC();
extern void sub_08069660();
extern void sub_08069684();
extern void sub_080696B0();
extern void sub_08069888();
extern void sub_0806991C();
extern void sub_080699AC();
extern void sub_08069A3C();
extern void sub_08069A60();
extern void sub_08069A84();
extern void sub_08069AA8();
extern void sub_08069ACC();
extern void sub_08069EE8();
extern void sub_0806A958();
extern void sub_0806A96C();
extern void sub_0806A9B0();
extern void sub_0806A9E8();
extern void sub_0806AA10();
extern void sub_0806AA18();
extern void sub_0806AA50();
extern void sub_0806AB74();
extern void sub_0806AED8();
extern void sub_0806AEE4();
extern void sub_0806AF60();
extern void sub_0806AF70();
extern void sub_0806AF78();
extern void sub_0806AFE8();
extern void sub_0806B260();
extern void sub_0806B2B4();
extern void sub_0806B4F0();
extern void sub_0806BA34();
extern void sub_0806BB1C();
extern void sub_0806BB7C();
extern void sub_0806BBB0();
extern void sub_0806BC94();
extern void sub_0806BCB8();
extern void sub_0806BCE8();
extern void sub_0806BE84();
extern void sub_0806BEC8();
extern void sub_0806BEFC();
extern void sub_0806BF44();
extern void sub_0806C00C();
extern void sub_0806C028();
extern void sub_0806C038();
extern void sub_0806C09C();
extern void sub_0806C224();
extern void sub_0806C280();
extern void sub_0806C2A0();
extern void sub_0806C4A8();
extern void sub_0806C4DC();
extern void sub_0806C578();
extern void sub_0806C588();
extern void sub_0806C598();
extern void sub_0806C70C();
extern void sub_0806C90C();
extern void sub_0806CA5C();
extern void sub_0806CCB4();
extern void sub_0806CCD0();
extern void sub_0806CCF8();
extern void sub_0806CD04();
extern void sub_0806CD14();
extern void sub_0806CD20();
extern void sub_0806CD30();
extern void sub_0806CD3C();
extern void sub_0806CD4C();
extern void sub_0806CE80();
extern void sub_0806D5D4();
extern void sub_0806D600();
extern void sub_0806D620();
extern void sub_0806D638();
extern void sub_0806D640();
extern void sub_0806D650();
extern void sub_0806D658();
extern void sub_0806D660();
extern void sub_0806D66C();
extern void sub_0806D67C();
extern void sub_0806D6D0();
extern void sub_0806D70C();
extern void sub_0806D74C();
extern void sub_0806D788();
extern void sub_0806D7C4();
extern void sub_0806D804();
extern void sub_0806D858();
extern void sub_0806D8A0();
extern void sub_0806D908();
extern void sub_0806D944();
extern void sub_0806D96C();
extern void sub_0806D9A4();
extern void sub_0806DB84();
extern void sub_0806DC7C();
extern void sub_0806DCA0();
extern void sub_0806DCC0();
extern void sub_0806E140();
extern void sub_0806E1E0();
extern void sub_0806E1FC();
extern void sub_0806E20C();
extern void sub_0806E23C();
extern void sub_0806E250();
extern void sub_0806E2DC();
extern void sub_0806E418();
extern void sub_0806E964();
extern void sub_0806EC38();
extern void sub_0807529C();
extern void sub_080752AC();
extern void sub_0807F1A0();
extern void sub_0807F1C4();
extern void sub_0807F1E8();
extern void sub_0807F210();
extern void sub_0807F36C();
extern void sub_0807F3C8();
extern void sub_0807F3D8();
extern void sub_0807F464();
extern void sub_0807F4F8();
extern void sub_0807F5B0();
extern void sub_0807F650();
extern void sub_0807F680();
extern void sub_0807F6B4();
extern void sub_0807F714();
extern void sub_0807F738();
extern void sub_0807F844();
extern void sub_0807F8E8();
extern void sub_0807F93C();
extern void sub_0807FADC();
extern void sub_0807FB28();
extern void sub_0807FBA0();
extern void sub_0807FBB4();
extern void sub_0807FBC4();
extern void sub_0807FBCC();
extern void sub_0807FBD4();
#ifndef EU
extern void sub_0807FBFC();
extern void sub_0807FC24();
#endif
extern void sub_0808692C();
extern void sub_080869A4();
extern void sub_080873FC();
extern void sub_08087424();
extern void sub_0808747C();
#ifndef EU
extern void sub_0808861C();
extern void sub_08088658();
#endif
extern void sub_0808D280();
extern void sub_0808D2CC();
extern void sub_08094AE8();
extern void sub_08094B0C();
extern void sub_08094B3C();
extern void sub_08094B6C();
extern void sub_08094B80();
extern void sub_08094B94();
extern void sub_08094BE0();
extern void sub_08094CDC();
extern void sub_08094D10();
extern void sub_08094D34();
extern void sub_08094D70();
extern void sub_08094DD8();
extern void sub_08094E0C();
extern void sub_08094F98();
extern void sub_08095164();
extern void sub_08095244();
extern void sub_08095330();
extern void sub_08095364();
extern void sub_08095420();
extern void sub_0809545C();
extern void sub_0809567C();
extern void sub_08095810();
extern void sub_08095A1C();
extern void sub_08095D54();
extern void sub_08095D8C();
extern void sub_08095E7C();
extern void sub_08095EAC();
extern void sub_08096028();
extern void sub_080960C4();
extern void sub_080961B0();
extern void sub_080962F8();
extern void sub_0809E0A0();
extern void sub_0809E0D4();
extern void sub_080A0464();
extern void sub_080A0B28();
extern void sub_080A1270();
extern void sub_080A1648();
extern void sub_080A169C();

typedef struct {
    u32 gba_addr;
    void (*func)(void);
} ScriptFuncEntry;

static const ScriptFuncEntry sScriptFuncTable[] = {
    { 0x08046079, (void(*)(void))sub_08046078 },
    { 0x0804BCDD, (void(*)(void))sub_0804BCDC },
    { 0x0804BF39, (void(*)(void))sub_0804BF38 },
    { 0x0804D7ED, (void(*)(void))sub_0804D7EC },
    { 0x0804D811, (void(*)(void))sub_0804D810 },
    { 0x0804E865, (void(*)(void))sub_0804E864 },
    { 0x0804F6A9, (void(*)(void))sub_0804F6A8 },
    { 0x0804F6C9, (void(*)(void))sub_0804F6C8 },
    { 0x0804F6E9, (void(*)(void))sub_0804F6E8 },
    { 0x0804F725, (void(*)(void))sub_0804F724 },
    { 0x0804F761, (void(*)(void))sub_0804F760 },
    { 0x0804F79D, (void(*)(void))sub_0804F79C },
    { 0x0804F809, (void(*)(void))sub_0804F808 },
    { 0x0804F831, (void(*)(void))sub_0804F830 },
    { 0x0804F855, (void(*)(void))sub_0804F854 },
    { 0x0804F89D, (void(*)(void))sub_0804F89C },
    { 0x0804F8E1, (void(*)(void))sub_0804F8E0 },
    { 0x0804F929, (void(*)(void))sub_0804F928 },
    { 0x0804F945, (void(*)(void))sub_0804F944 },
    { 0x0804F961, (void(*)(void))sub_0804F960 },
    { 0x0804F995, (void(*)(void))sub_0804F994 },
    { 0x0804F9C9, (void(*)(void))sub_0804F9C8 },
    { 0x08053251, (void(*)(void))sub_08053250 },
    { 0x08053495, (void(*)(void))StartDarkNutTimer },
    { 0x08053635, (void(*)(void))sub_08053634 },
    { 0x08053649, (void(*)(void))sub_08053648 },
    { 0x0805367D, (void(*)(void))sub_0805367C },
    { 0x0805368D, (void(*)(void))sub_0805368C },
    { 0x080536A9, (void(*)(void))sub_080536A8 },
    { 0x080536B9, (void(*)(void))sub_080536B8 },
    { 0x08053B3D, (void(*)(void))sub_08053B3C },
    { 0x08053BE9, (void(*)(void))sub_08053BE8 },
    { 0x08053C85, (void(*)(void))sub_08053C84 },
    { 0x08054565, (void(*)(void))DisableRandomDrops },
    { 0x08054571, (void(*)(void))EnableRandomDrops },
    { 0x08054969, (void(*)(void))sub_08054968 },
    { 0x0805DDED, (void(*)(void))CreateRepeatedSoundManager },
    { 0x0805DE19, (void(*)(void))DeleteRepeatedSoundManager },
    { 0x0805E545, (void(*)(void))SetPlayerEventPriority },
    { 0x0805E565, (void(*)(void))ResetPlayerEventPriority },
    { 0x0805EBCD, (void(*)(void))DeleteAllEnemies },
    { 0x08060091, (void(*)(void))ForestMinish_MakeInteractable },
    { 0x0806014D, (void(*)(void))sub_0806014C },
    { 0x08060159, (void(*)(void))sub_08060158 },
    { 0x08060209, (void(*)(void))sub_08060208 },
    { 0x0806021D, (void(*)(void))sub_0806021C },
    { 0x0806025D, (void(*)(void))sub_0806025C },
    { 0x08060271, (void(*)(void))sub_08060270 },
    { 0x080602BD, (void(*)(void))sub_080602BC },
    { 0x0806030D, (void(*)(void))script_ModBombs },
    { 0x08060319, (void(*)(void))sub_08060318 },
    { 0x08060341, (void(*)(void))sub_08060340 },
    { 0x080606C1, (void(*)(void))Postman_MakeInteractable },
    { 0x08060701, (void(*)(void))sub_08060700 },
    { 0x0806075D, (void(*)(void))sub_0806075C },
    { 0x0806076D, (void(*)(void))sub_0806076C },
    { 0x080608E5, (void(*)(void))sub_080608E4 },
    { 0x08061E71, (void(*)(void))Townsperson_MakeInteractable },
    { 0x08061E91, (void(*)(void))sub_08061E90 },
    { 0x08061F95, (void(*)(void))sub_08061F94 },
    { 0x08061FB1, (void(*)(void))sub_08061FB0 },
    { 0x08061FB9, (void(*)(void))sub_08061FB8 },
    { 0x08061FD9, (void(*)(void))sub_08061FD8 },
    { 0x08061FE5, (void(*)(void))sub_08061FE4 },
    { 0x08061FF5, (void(*)(void))sub_08061FF4 },
    { 0x0806200D, (void(*)(void))sub_0806200C },
    { 0x08062049, (void(*)(void))sub_08062048 },
    { 0x08062501, (void(*)(void))sub_08062500 },
    { 0x0806265D, (void(*)(void))sub_0806265C },
    { 0x08062699, (void(*)(void))sub_08062698 },
    { 0x080626AD, (void(*)(void))sub_080626AC },
    { 0x080626C1, (void(*)(void))sub_080626C0 },
    { 0x08062789, (void(*)(void))sub_08062788 },
    { 0x080627E9, (void(*)(void))sub_080627E8 },
    { 0x08062949, (void(*)(void))sub_08062948 },
    { 0x08062A49, (void(*)(void))Kid_MakeInteractable },
    { 0x08062CBD, (void(*)(void))sub_08062CBC },
    { 0x08062D19, (void(*)(void))sub_08062D18 },
    { 0x08062E15, (void(*)(void))sub_08062E14 },
    { 0x08062EB9, (void(*)(void))RemoveAllBakedGoods },
    { 0x08062EDD, (void(*)(void))sub_08062EDC },
    { 0x0806305D, (void(*)(void))sub_0806305C },
    { 0x080630A5, (void(*)(void))sub_080630A4 },
    { 0x080634E5, (void(*)(void))Beedle_GetObjectType },
    { 0x080634ED, (void(*)(void))Beedle_ConfirmBuyItem },
    { 0x08063505, (void(*)(void))Beedle_IsBottleInInventory },
    { 0x080636D9, (void(*)(void))sub_080636D8 },
    { 0x080636F5, (void(*)(void))Brocco_MakeInteractable },
    { 0x08063851, (void(*)(void))sub_08063850 },
    { 0x08063875, (void(*)(void))sub_08063874 },
    { 0x08063945, (void(*)(void))SittingPersion_ShowDialogue },
    { 0x080639D1, (void(*)(void))SittingPerson_MakeInteractable },
    { 0x08063C15, (void(*)(void))sub_08063C14 },
    { 0x08063C2D, (void(*)(void))sub_08063C2C },
    { 0x08063C45, (void(*)(void))sub_08063C44 },
    { 0x08063C5D, (void(*)(void))sub_08063C5C },
    { 0x08063C75, (void(*)(void))sub_08063C74 },
    { 0x08063C91, (void(*)(void))sub_08063C90 },
    { 0x08063CAD, (void(*)(void))Pina_MakeInteractable },
    { 0x08064051, (void(*)(void))sub_08064050 },
    { 0x0806407D, (void(*)(void))sub_0806407C },
    { 0x08064181, (void(*)(void))sub_08064180 },
    { 0x08064199, (void(*)(void))sub_08064198 },
    { 0x080642B9, (void(*)(void))sub_080642B8 },
    { 0x080643D9, (void(*)(void))sub_080643D8 },
    { 0x08064429, (void(*)(void))sub_08064428 },
    { 0x08064471, (void(*)(void))GuardWithSpear_CheckSwordMoveSpin },
    { 0x08064489, (void(*)(void))GuardWithSpear_ResetLastSwordMoveIfNotInSwordState },
    { 0x080644A5, (void(*)(void))GuardWithSpear_ResetLastSwordMove },
    { 0x080644B5, (void(*)(void))CheckLastSwordMove },
    { 0x08064645, (void(*)(void))CastleMaid_SetDialogFunc },
    { 0x080646A5, (void(*)(void))sub_080646A4 },
    { 0x08064829, (void(*)(void))Din_MakeInteractable },
    { 0x08064929, (void(*)(void))Nayru_MakeInteractable },
    { 0x08064A29, (void(*)(void))Farore_MakeInteractable },
    { 0x08064CC1, (void(*)(void))Sturgeon_MakeInteractable },
    { 0x08064CD9, (void(*)(void))sub_08064CD8 },
    { 0x08064D09, (void(*)(void))sub_08064D08 },
    { 0x08064D11, (void(*)(void))sub_08064D10 },
    { 0x08064EA5, (void(*)(void))TingleSiblings_MakeInteractable },
    { 0x08064F29, (void(*)(void))sub_08064F28 },
    { 0x08065371, (void(*)(void))sub_08065370 },
    { 0x080654DD, (void(*)(void))sub_080654DC },
    { 0x080654ED, (void(*)(void))sub_080654EC },
    { 0x080654FD, (void(*)(void))sub_080654FC },
    { 0x08065529, (void(*)(void))sub_08065528 },
    { 0x08065781, (void(*)(void))sub_08065780 },
    { 0x08065915, (void(*)(void))sub_08065914 },
    { 0x08065CCD, (void(*)(void))sub_08065CCC },
    { 0x08065D01, (void(*)(void))GhostBrothers_MakeInteractable },
    { 0x08065F65, (void(*)(void))sub_08065F64 },
    { 0x0806622D, (void(*)(void))sub_0806622C },
    { 0x08066259, (void(*)(void))sub_08066258 },
    { 0x08066275, (void(*)(void))Smith_ChangeInteractableHitbox },
    { 0x08066289, (void(*)(void))Smith_MakeInteractable },
    { 0x0806672D, (void(*)(void))KingDaltus_MakeInteractable },
    { 0x0806673D, (void(*)(void))sub_0806673C },
    { 0x080668F1, (void(*)(void))MinisterPotho_MakeInteractable },
    { 0x08066905, (void(*)(void))sub_08066904 },
    { 0x08066C95, (void(*)(void))Vaati_Apparate },
    { 0x08066CA5, (void(*)(void))Vaati_Evaporate },
    { 0x08066D05, (void(*)(void))sub_08066D04 },
    { 0x08066D15, (void(*)(void))sub_08066D14 },
    { 0x08066D4D, (void(*)(void))sub_08066D4C },
    { 0x08066E09, (void(*)(void))sub_08066E08 },
    { 0x08066E21, (void(*)(void))sub_08066E20 },
    { 0x08066E39, (void(*)(void))sub_08066E38 },
    { 0x08066E51, (void(*)(void))sub_08066E50 },
    { 0x08066E69, (void(*)(void))sub_08066E68 },
    { 0x08066E81, (void(*)(void))sub_08066E80 },
    { 0x08066F95, (void(*)(void))sub_08066F94 },
    { 0x08066FB9, (void(*)(void))sub_08066FB8 },
    { 0x080670B5, (void(*)(void))sub_080670B4 },
    { 0x080670E5, (void(*)(void))sub_080670E4 },
    { 0x08067101, (void(*)(void))Mutoh_MakeInteractable },
    { 0x080672B1, (void(*)(void))sub_080672B0 },
    { 0x080672C9, (void(*)(void))sub_080672C8 },
    { 0x08067305, (void(*)(void))sub_08067304 },
    { 0x08067315, (void(*)(void))Carpenter_MakeInteractable },
    { 0x08067535, (void(*)(void))sub_08067534 },
    { 0x0806757D, (void(*)(void))sub_0806757C },
    { 0x080675D5, (void(*)(void))sub_080675D4 },
    { 0x080676D9, (void(*)(void))sub_080676D8 },
    { 0x080676E1, (void(*)(void))sub_080676E0 },
    { 0x08068105, (void(*)(void))MountainMinish_MakeInteractable },
    { 0x0806811D, (void(*)(void))sub_0806811C },
    { 0x08068191, (void(*)(void))sub_08068190 },
    { 0x080681D9, (void(*)(void))sub_080681D8 },
    { 0x08068885, (void(*)(void))Melari_MakeInteractable },
    { 0x08068911, (void(*)(void))sub_08068910 },
    { 0x08068965, (void(*)(void))sub_08068964 },
    { 0x08068B85, (void(*)(void))BladeBrothers_StartPlayerDemonstration },
    { 0x08068BB5, (void(*)(void))sub_08068BB4 },
    { 0x08068BD1, (void(*)(void))sub_08068BD0 },
    { 0x08068C29, (void(*)(void))sub_08068C28 },
    { 0x08068C6D, (void(*)(void))BladeBrothers_GetScroll },
    { 0x08068C8D, (void(*)(void))sub_08068C8C },
    { 0x08068CA1, (void(*)(void))sub_08068CA0 },
    { 0x08068CFD, (void(*)(void))sub_08068CFC },
    { 0x08068DB9, (void(*)(void))sub_08068DB8 },
    { 0x08068DD1, (void(*)(void))sub_08068DD0 },
    { 0x08068DE9, (void(*)(void))sub_08068DE8 },
    { 0x08068E01, (void(*)(void))sub_08068E00 },
    { 0x08068E19, (void(*)(void))sub_08068E18 },
    { 0x08068E31, (void(*)(void))sub_08068E30 },
    { 0x08068E49, (void(*)(void))sub_08068E48 },
    { 0x08068E61, (void(*)(void))sub_08068E60 },
    { 0x08068E79, (void(*)(void))sub_08068E78 },
    { 0x08068E91, (void(*)(void))BladeBrothers_LearnSkill },
    { 0x08068EB5, (void(*)(void))BladeBrothers_ResetLastSwordMove },
    { 0x08068EC5, (void(*)(void))BladeBrothers_CheckLastSwordMove },
    { 0x08068F01, (void(*)(void))sub_08068F00 },
    { 0x08068F15, (void(*)(void))sub_08068F14 },
    { 0x08068F3D, (void(*)(void))sub_08068F3C },
    { 0x0806948D, (void(*)(void))sub_0806948C },
    { 0x080694B1, (void(*)(void))Goron_MakeInteractable },
    { 0x080694D9, (void(*)(void))sub_080694D8 },
    { 0x080694ED, (void(*)(void))sub_080694EC },
    { 0x08069661, (void(*)(void))sub_08069660 },
    { 0x08069685, (void(*)(void))sub_08069684 },
    { 0x080696B1, (void(*)(void))sub_080696B0 },
    { 0x08069719, (void(*)(void))GoronMerchant_TryToBuyKinstone },
    { 0x08069889, (void(*)(void))sub_08069888 },
    { 0x0806991D, (void(*)(void))sub_0806991C },
    { 0x080699AD, (void(*)(void))sub_080699AC },
    { 0x08069A3D, (void(*)(void))sub_08069A3C },
    { 0x08069A61, (void(*)(void))sub_08069A60 },
    { 0x08069A85, (void(*)(void))sub_08069A84 },
    { 0x08069AA9, (void(*)(void))sub_08069AA8 },
    { 0x08069ACD, (void(*)(void))sub_08069ACC },
    { 0x08069EE9, (void(*)(void))sub_08069EE8 },
    { 0x0806A93D, (void(*)(void))Rem_MakeInteractable },
    { 0x0806A959, (void(*)(void))sub_0806A958 },
    { 0x0806A96D, (void(*)(void))sub_0806A96C },
    { 0x0806A9B1, (void(*)(void))sub_0806A9B0 },
    { 0x0806A9E9, (void(*)(void))sub_0806A9E8 },
    { 0x0806AA11, (void(*)(void))sub_0806AA10 },
    { 0x0806AA19, (void(*)(void))sub_0806AA18 },
    { 0x0806AA51, (void(*)(void))sub_0806AA50 },
    { 0x0806AB75, (void(*)(void))sub_0806AB74 },
    { 0x0806AB9D, (void(*)(void))DeleteNpcRem },
    { 0x0806ADFD, (void(*)(void))TownMinish_MakeInteractable },
    { 0x0806AED9, (void(*)(void))sub_0806AED8 },
    { 0x0806AEE5, (void(*)(void))sub_0806AEE4 },
    { 0x0806AF61, (void(*)(void))sub_0806AF60 },
    { 0x0806AF71, (void(*)(void))sub_0806AF70 },
    { 0x0806AF79, (void(*)(void))sub_0806AF78 },
    { 0x0806AFE9, (void(*)(void))sub_0806AFE8 },
    { 0x0806B261, (void(*)(void))sub_0806B260 },
    { 0x0806B2B5, (void(*)(void))sub_0806B2B4 },
    { 0x0806B4F1, (void(*)(void))sub_0806B4F0 },
    { 0x0806B60D, (void(*)(void))Percy_MakeInteractable },
    { 0x0806BA35, (void(*)(void))sub_0806BA34 },
    { 0x0806BB1D, (void(*)(void))sub_0806BB1C },
    { 0x0806BB7D, (void(*)(void))sub_0806BB7C },
    { 0x0806BBB1, (void(*)(void))sub_0806BBB0 },
    { 0x0806BC95, (void(*)(void))sub_0806BC94 },
    { 0x0806BCB9, (void(*)(void))sub_0806BCB8 },
    { 0x0806BCC1, (void(*)(void))Farmers_MarkEenieFuserDoner },
    { 0x0806BCD5, (void(*)(void))Farmers_MakeInteractable },
    { 0x0806BCE9, (void(*)(void))sub_0806BCE8 },
    { 0x0806BE3D, (void(*)(void))Dampe_MakeInteractable },
    { 0x0806BE85, (void(*)(void))sub_0806BE84 },
    { 0x0806BEC9, (void(*)(void))sub_0806BEC8 },
    { 0x0806BEFD, (void(*)(void))sub_0806BEFC },
    { 0x0806BF45, (void(*)(void))sub_0806BF44 },
    { 0x0806C00D, (void(*)(void))sub_0806C00C },
    { 0x0806C029, (void(*)(void))sub_0806C028 },
    { 0x0806C039, (void(*)(void))sub_0806C038 },
    { 0x0806C09D, (void(*)(void))sub_0806C09C },
    { 0x0806C225, (void(*)(void))sub_0806C224 },
    { 0x0806C23D, (void(*)(void))Simon_CreateChest },
    { 0x0806C281, (void(*)(void))sub_0806C280 },
    { 0x0806C2A1, (void(*)(void))sub_0806C2A0 },
    { 0x0806C355, (void(*)(void))Anju_MakeInteractable },
    { 0x0806C4A9, (void(*)(void))sub_0806C4A8 },
    { 0x0806C4DD, (void(*)(void))sub_0806C4DC },
    { 0x0806C4F9, (void(*)(void))Mama_MakeInteractable },
    { 0x0806C579, (void(*)(void))sub_0806C578 },
    { 0x0806C589, (void(*)(void))sub_0806C588 },
    { 0x0806C599, (void(*)(void))sub_0806C598 },
    { 0x0806C675, (void(*)(void))Teachers_MakeInteractable },
    { 0x0806C70D, (void(*)(void))sub_0806C70C },
    { 0x0806C871, (void(*)(void))WindTribespeople_MakeInteractable },
    { 0x0806C90D, (void(*)(void))sub_0806C90C },
    { 0x0806CA5D, (void(*)(void))sub_0806CA5C },
    { 0x0806CCB5, (void(*)(void))sub_0806CCB4 },
    { 0x0806CCD1, (void(*)(void))sub_0806CCD0 },
    { 0x0806CCF9, (void(*)(void))sub_0806CCF8 },
    { 0x0806CD05, (void(*)(void))sub_0806CD04 },
    { 0x0806CD15, (void(*)(void))sub_0806CD14 },
    { 0x0806CD21, (void(*)(void))sub_0806CD20 },
    { 0x0806CD31, (void(*)(void))sub_0806CD30 },
    { 0x0806CD3D, (void(*)(void))sub_0806CD3C },
    { 0x0806CD4D, (void(*)(void))sub_0806CD4C },
    { 0x0806CD59, (void(*)(void))Gregal_MakeInteractable },
    { 0x0806CE5D, (void(*)(void))MayorHagen_MakeInteractable },
    { 0x0806CE81, (void(*)(void))sub_0806CE80 },
    { 0x0806D5D5, (void(*)(void))sub_0806D5D4 },
    { 0x0806D601, (void(*)(void))sub_0806D600 },
    { 0x0806D621, (void(*)(void))sub_0806D620 },
    { 0x0806D639, (void(*)(void))sub_0806D638 },
    { 0x0806D641, (void(*)(void))sub_0806D640 },
    { 0x0806D651, (void(*)(void))sub_0806D650 },
    { 0x0806D659, (void(*)(void))sub_0806D658 },
    { 0x0806D661, (void(*)(void))sub_0806D660 },
    { 0x0806D66D, (void(*)(void))sub_0806D66C },
    { 0x0806D67D, (void(*)(void))sub_0806D67C },
    { 0x0806D6D1, (void(*)(void))sub_0806D6D0 },
    { 0x0806D70D, (void(*)(void))sub_0806D70C },
    { 0x0806D74D, (void(*)(void))sub_0806D74C },
    { 0x0806D789, (void(*)(void))sub_0806D788 },
    { 0x0806D7C5, (void(*)(void))sub_0806D7C4 },
    { 0x0806D805, (void(*)(void))sub_0806D804 },
    { 0x0806D859, (void(*)(void))sub_0806D858 },
    { 0x0806D8A1, (void(*)(void))sub_0806D8A0 },
    { 0x0806D909, (void(*)(void))sub_0806D908 },
    { 0x0806D945, (void(*)(void))sub_0806D944 },
    { 0x0806D96D, (void(*)(void))sub_0806D96C },
    { 0x0806D9A5, (void(*)(void))sub_0806D9A4 },
    { 0x0806DA05, (void(*)(void))NPC4E_ChangeInteractableHitbox },
    { 0x0806DA1D, (void(*)(void))NPC4E_DoScreenTransition },
    { 0x0806DAAD, (void(*)(void))NPC4E_IsKinstoneFused },
    { 0x0806DAD1, (void(*)(void))NPC4E_MakeFuserInteractable },
    { 0x0806DAE9, (void(*)(void))NPC4E_SetPinwheelFlag },
    { 0x0806DB45, (void(*)(void))NPC4E_IsEveryPinwheelActivated },
    { 0x0806DB85, (void(*)(void))sub_0806DB84 },
    { 0x0806DC3D, (void(*)(void))NPC4E_SaveEquippedItems },
    { 0x0806DC59, (void(*)(void))NPC4E_RestoreEquippedItems },
    { 0x0806DC7D, (void(*)(void))sub_0806DC7C },
    { 0x0806DCA1, (void(*)(void))sub_0806DCA0 },
    { 0x0806DCC1, (void(*)(void))sub_0806DCC0 },
    { 0x0806E141, (void(*)(void))sub_0806E140 },
    { 0x0806E1E1, (void(*)(void))sub_0806E1E0 },
    { 0x0806E1FD, (void(*)(void))sub_0806E1FC },
    { 0x0806E20D, (void(*)(void))sub_0806E20C },
    { 0x0806E23D, (void(*)(void))sub_0806E23C },
    { 0x0806E251, (void(*)(void))sub_0806E250 },
    { 0x0806E2DD, (void(*)(void))sub_0806E2DC },
    { 0x0806E419, (void(*)(void))sub_0806E418 },
    { 0x0806E441, (void(*)(void))HurdyGurdyMan_MakeInteractable },
    { 0x0806E965, (void(*)(void))sub_0806E964 },
    { 0x0806EC39, (void(*)(void))sub_0806EC38 },
    { 0x0806F189, (void(*)(void))MarkFuserDone },
    { 0x0807529D, (void(*)(void))sub_0807529C },
    { 0x080752AD, (void(*)(void))sub_080752AC },
    { 0x080787B5, (void(*)(void))AddInteractableCheckableObject },
    { 0x08079185, (void(*)(void))PlayerDropHeldObject },
    { 0x080791BD, (void(*)(void))SetPlayerActionNormal },
    { 0x080791D1, (void(*)(void))ResetPlayerAnimationAndAction },
    { 0x0807921D, (void(*)(void))PlayerSetNormalAndCollide },
    { 0x0807AEE5, (void(*)(void))UpdatePlayerSkills },
    { 0x0807DF29, (void(*)(void))DisablePauseMenuAndPutAwayItems },
    { 0x0807DF39, (void(*)(void))DisablePauseMenu },
    { 0x0807DF51, (void(*)(void))EnablePauseMenu },
    { 0x0807F0D9, (void(*)(void))CheckAnyKeyPressed },
    { 0x0807F0ED, (void(*)(void))GetRandomInt },
    { 0x0807F159, (void(*)(void))SetCollisionLayer1 },
    { 0x0807F169, (void(*)(void))SetPlayerCollisionLayer1 },
    { 0x0807F181, (void(*)(void))SetCollisionLayer2 },
    { 0x0807F1A1, (void(*)(void))sub_0807F1A0 },
    { 0x0807F1C5, (void(*)(void))sub_0807F1C4 },
    { 0x0807F1E9, (void(*)(void))sub_0807F1E8 },
    { 0x0807F211, (void(*)(void))sub_0807F210 },
    { 0x0807F239, (void(*)(void))SetPlayerAnimation2 },
    { 0x0807F245, (void(*)(void))EquipItem },
    { 0x0807F29D, (void(*)(void))SetPlayerMacro },
    { 0x0807F2A9, (void(*)(void))WaitForPlayerMacro },
    { 0x0807F2D5, (void(*)(void))WaitForAnimDone },
    { 0x0807F305, (void(*)(void))WaitForPlayerAnim },
    { 0x0807F339, (void(*)(void))DeleteHitbox },
    { 0x0807F349, (void(*)(void))SetPriorityMessage },
    { 0x0807F355, (void(*)(void))SetPriorityPlayerEvent },
    { 0x0807F361, (void(*)(void))SetPriorityHighest },
    { 0x0807F36D, (void(*)(void))sub_0807F36C },
    { 0x0807F3C9, (void(*)(void))sub_0807F3C8 },
    { 0x0807F3D9, (void(*)(void))sub_0807F3D8 },
    { 0x0807F3F9, (void(*)(void))CreatePlayerExclamationMark },
    { 0x0807F40D, (void(*)(void))CreatePlayerQuestionMark },
    { 0x0807F421, (void(*)(void))LoadMenu },
    { 0x0807F435, (void(*)(void))CheckInteractType },
    { 0x0807F465, (void(*)(void))sub_0807F464 },
    { 0x0807F4F9, (void(*)(void))sub_0807F4F8 },
    { 0x0807F585, (void(*)(void))ReadPlayerAnimationState },
    { 0x0807F595, (void(*)(void))WaitForPlayerIdle },
    { 0x0807F5B1, (void(*)(void))sub_0807F5B0 },
    { 0x0807F5C1, (void(*)(void))WaitForCameraTouchRoomBorder },
    { 0x0807F651, (void(*)(void))sub_0807F650 },
    { 0x0807F681, (void(*)(void))sub_0807F680 },
    { 0x0807F6B5, (void(*)(void))sub_0807F6B4 },
    { 0x0807F6E9, (void(*)(void))SetPlayerFlag },
    { 0x0807F6F9, (void(*)(void))ResetPlayerFlag },
    { 0x0807F715, (void(*)(void))sub_0807F714 },
    { 0x0807F739, (void(*)(void))sub_0807F738 },
    { 0x0807F75D, (void(*)(void))SetPlayerPos },
    { 0x0807F77D, (void(*)(void))GetConditionSet },
    { 0x0807F78D, (void(*)(void))ScriptCommand_SaleItemConfirmMessage },
    { 0x0807F7C5, (void(*)(void))ScriptCommand_CheckShopItemPrice },
    { 0x0807F801, (void(*)(void))ScriptCommand_BuyShopItem },
    { 0x0807F83D, (void(*)(void))ScriptCommand_PlayerDropHeldObject },
    { 0x0807F845, (void(*)(void))sub_0807F844 },
    { 0x0807F855, (void(*)(void))ScriptCommand_SetMessageValue },
    { 0x0807F8BD, (void(*)(void))CheckEntityOnScreen },
    { 0x0807F8D1, (void(*)(void))DoGravity },
    { 0x0807F8E9, (void(*)(void))sub_0807F8E8 },
    { 0x0807F919, (void(*)(void))PutItemAnySlot },
    { 0x0807F925, (void(*)(void))MakeInteractableAsMinish },
    { 0x0807F92D, (void(*)(void))MakePedestalInteractable },
    { 0x0807F935, (void(*)(void))MakeCheckableObjectInteractable },
    { 0x0807F93D, (void(*)(void))sub_0807F93C },
    { 0x0807F971, (void(*)(void))CheckMessageEqual },
    { 0x0807F98D, (void(*)(void))SetEntityHeight },
    { 0x0807F995, (void(*)(void))SetSpriteOffset },
    { 0x0807F9A5, (void(*)(void))WaitForPlayerNormal },
    { 0x0807FA41, (void(*)(void))WaitForPlayerNormalOrTalkEzlo },
    { 0x0807FADD, (void(*)(void))sub_0807FADC },
    { 0x0807FB29, (void(*)(void))sub_0807FB28 },
    { 0x0807FB65, (void(*)(void))SetPlayerIFrames },
    { 0x0807FB75, (void(*)(void))DisablePlayerSwimState },
    { 0x0807FBA1, (void(*)(void))sub_0807FBA0 },
    { 0x0807FBB5, (void(*)(void))sub_0807FBB4 },
    { 0x0807FBC5, (void(*)(void))sub_0807FBC4 },
    { 0x0807FBCD, (void(*)(void))sub_0807FBCC },
    { 0x0807FBD5, (void(*)(void))sub_0807FBD4 },
#ifndef EU
    { 0x0807FBFD, (void(*)(void))sub_0807FBFC },
    { 0x0807FC25, (void(*)(void))sub_0807FC24 },
#endif
    { 0x0808692D, (void(*)(void))sub_0808692C },
    { 0x080869A5, (void(*)(void))sub_080869A4 },
    { 0x080873FD, (void(*)(void))sub_080873FC },
    { 0x08087425, (void(*)(void))sub_08087424 },
    { 0x0808747D, (void(*)(void))sub_0808747C },
    { 0x08088479, (void(*)(void))FigurineDevice_NoFigurinesLeftMessage },
    { 0x08088505, (void(*)(void))FigurineDevice_NothingNewToDrawMessage },
    { 0x08088545, (void(*)(void))FigurineDevice_NewFigurinesMessage },
    { 0x08088575, (void(*)(void))FigurineDevice_TryAgainMessage },
    { 0x080885B1, (void(*)(void))FigurineDevice_LostOrFinishedMessage },
#ifndef EU
    { 0x0808861D, (void(*)(void))sub_0808861C },
    { 0x08088659, (void(*)(void))sub_08088658 },
#endif
    { 0x0808D281, (void(*)(void))sub_0808D280 },
    { 0x0808D2CD, (void(*)(void))sub_0808D2CC },
    { 0x08094AE9, (void(*)(void))sub_08094AE8 },
    { 0x08094B0D, (void(*)(void))sub_08094B0C },
    { 0x08094B3D, (void(*)(void))sub_08094B3C },
    { 0x08094B6D, (void(*)(void))sub_08094B6C },
    { 0x08094B81, (void(*)(void))sub_08094B80 },
    { 0x08094B95, (void(*)(void))sub_08094B94 },
    { 0x08094BE1, (void(*)(void))sub_08094BE0 },
    { 0x08094CDD, (void(*)(void))sub_08094CDC },
    { 0x08094D11, (void(*)(void))sub_08094D10 },
    { 0x08094D35, (void(*)(void))sub_08094D34 },
    { 0x08094D71, (void(*)(void))sub_08094D70 },
    { 0x08094DD9, (void(*)(void))sub_08094DD8 },
    { 0x08094E0D, (void(*)(void))sub_08094E0C },
    { 0x08094F99, (void(*)(void))sub_08094F98 },
    { 0x08095165, (void(*)(void))sub_08095164 },
    { 0x08095245, (void(*)(void))sub_08095244 },
    { 0x08095331, (void(*)(void))sub_08095330 },
    { 0x08095365, (void(*)(void))sub_08095364 },
    { 0x08095421, (void(*)(void))sub_08095420 },
    { 0x08095459, (void(*)(void))nullsub_527 },
    { 0x0809545D, (void(*)(void))sub_0809545C },
    { 0x0809567D, (void(*)(void))sub_0809567C },
    { 0x08095811, (void(*)(void))sub_08095810 },
    { 0x08095A1D, (void(*)(void))sub_08095A1C },
    { 0x08095D55, (void(*)(void))sub_08095D54 },
    { 0x08095D8D, (void(*)(void))sub_08095D8C },
    { 0x08095E7D, (void(*)(void))sub_08095E7C },
    { 0x08095EAD, (void(*)(void))sub_08095EAC },
    { 0x08096029, (void(*)(void))sub_08096028 },
    { 0x080960C5, (void(*)(void))sub_080960C4 },
    { 0x080961B1, (void(*)(void))sub_080961B0 },
    { 0x080962F9, (void(*)(void))sub_080962F8 },
    { 0x0809E0A1, (void(*)(void))sub_0809E0A0 },
    { 0x0809E0D5, (void(*)(void))sub_0809E0D4 },
    { 0x080A0465, (void(*)(void))sub_080A0464 },
    { 0x080A0B29, (void(*)(void))sub_080A0B28 },
    { 0x080A1271, (void(*)(void))sub_080A1270 },
    { 0x080A1389, (void(*)(void))CuccoMinigame_Cleanup },
    { 0x080A13B5, (void(*)(void))CuccoMinigame_Results },
    { 0x080A13E9, (void(*)(void))CuccoMinigame_WinItem },
    { 0x080A1461, (void(*)(void))CuccoMinigame_WinRupees },
    { 0x080A14A9, (void(*)(void))CuccoMinigame_AdvanceLevel },
    { 0x080A1551, (void(*)(void))CuccoMinigame_Init },
    { 0x080A1609, (void(*)(void))CuccoMinigame_TellObjective },
    { 0x080A1649, (void(*)(void))sub_080A1648 },
    { 0x080A169D, (void(*)(void))sub_080A169C },
    { 0x080A2125, (void(*)(void))Windcrest_ChangeInteractableHitbox },
    { 0x080A2139, (void(*)(void))Windcrest_Unlock },
    { 0x080A29BD, (void(*)(void))CreateDust },
};

#define SCRIPT_FUNC_TABLE_SIZE (sizeof(sScriptFuncTable) / sizeof(sScriptFuncTable[0]))

/**
 * Look up a PC function pointer from a GBA Thumb address.
 * Returns NULL if not found.
 */
void* Port_LookupScriptFunc(u32 gba_addr) {
    int lo = 0, hi = SCRIPT_FUNC_TABLE_SIZE - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (sScriptFuncTable[mid].gba_addr == gba_addr)
            return (void*)sScriptFuncTable[mid].func;
        else if (sScriptFuncTable[mid].gba_addr < gba_addr)
            lo = mid + 1;
        else
            hi = mid - 1;
    }
    return NULL;
}
