#!/usr/bin/env python3
"""Extract the tmc_pc source list from xmake.lua and expand globs into a
Makefile fragment (sources.mk) for the Switch build.

The PC port compiles only a *subset* of the decomp's src/ tree, so we must
mirror xmake's explicit add_files() list rather than globbing src/**.
Run from the repo root (platforms/switch/gen_sources.py invokes it that way).
"""
import os
import re
import sys
import glob

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def extract_tmc_pc_addfiles(xmake_lua: str):
    """Return the list of add_files() glob arguments inside the tmc_pc target."""
    with open(xmake_lua, "r", encoding="utf-8") as f:
        text = f.read()

    # Slice out the tmc_pc target block.
    start = text.index('target("tmc_pc")')
    end = text.index("target_end()", start)
    block = text[start:end]

    # Drop Lua line comments so commented-out add_files() (e.g. the
    # deliberately-excluded src/gba/m4a.c) are not picked up.
    lines = []
    for line in block.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("--"):
            continue
        lines.append(line)
    block = "\n".join(lines)

    # add_files("path/glob") possibly multiple per line.
    return re.findall(r'add_files\(\s*"([^"]+)"', block)


def main():
    patterns = extract_tmc_pc_addfiles(os.path.join(REPO_ROOT, "xmake.lua"))

    c_sources = []
    cpp_sources = []
    seen = set()
    for pat in patterns:
        # xmake globs are relative to the repo root.
        matches = sorted(glob.glob(os.path.join(REPO_ROOT, pat)))
        if not matches:
            print(f"  WARN: no match for {pat}", file=sys.stderr)
        for m in matches:
            rel = os.path.relpath(m, REPO_ROOT).replace(os.sep, "/")
            if rel in seen:
                continue
            seen.add(rel)
            if rel.endswith(".c"):
                c_sources.append(rel)
            elif rel.endswith(".cpp"):
                cpp_sources.append(rel)

    out = os.path.join(os.path.dirname(__file__), "sources.mk")
    with open(out, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by gen_sources.py from xmake.lua tmc_pc target.\n")
        f.write("# Do not edit by hand; re-run gen_sources.py to refresh.\n\n")
        f.write("C_SOURCES := \\\n")
        for s in c_sources:
            f.write(f"\t{s} \\\n")
        f.write("\n")
        f.write("CPP_SOURCES := \\\n")
        for s in cpp_sources:
            f.write(f"\t{s} \\\n")
        f.write("\n")

    print(f"Wrote {out}: {len(c_sources)} C, {len(cpp_sources)} C++ sources")


if __name__ == "__main__":
    main()
