#!/usr/bin/env python3
"""
generate_asset_index.py — (re)generate port/port_asset_index*.c from a region
manifest emitted by the asset_processor (run with TMC_ASSET_MANIFEST set).

The committed port_asset_index.c is USA-only (absolute USA ROM offsets). The EU
build needs EU offsets or the asset_extractor reads every asset from the wrong
place in the EU ROM. The asset_processor already resolves each asset's
region-correct ROM offset (asset["offsets"][VARIANT] + handler getStart()), so
we dump a manifest from it and rebuild the index per region.

Usage:
    generate_asset_index.py validate <usa_manifest.csv>
        -> check the USA manifest reproduces the committed port_asset_index.c
    generate_asset_index.py emit <eu_manifest.csv> <out.c> [usa_manifest.csv]
        -> write port_asset_index_eu.c (offsets from the EU manifest; the entry
           SET + paths are taken from the committed index so the runtime lookups
           are identical, only the offsets change)
"""
import sys, re

INDEX = 'port/port_asset_index.c'

def parse_index(path):
    """Return ordered list of (offset, size, path) from the committed C index."""
    txt = open(path, encoding='utf-8', errors='replace').read()
    out = []
    for m in re.finditer(r'\{\s*0x([0-9A-Fa-f]+)\s*,\s*0x([0-9A-Fa-f]+)\s*,\s*"([^"]+)"\s*\}', txt):
        out.append((int(m.group(1), 16), int(m.group(2), 16), m.group(3)))
    return out

def parse_manifest(path):
    """Return dict path -> (offset, size). Last write wins (extract order)."""
    d = {}
    for line in open(path, encoding='utf-8', errors='replace'):
        line = line.rstrip('\n')
        if not line:
            continue
        a, b, p = line.split(',', 2)
        d[p] = (int(a), int(b))
    return d

def validate(usa_manifest):
    idx = parse_index(INDEX)
    man = parse_manifest(usa_manifest)
    print('index entries: %d   manifest entries: %d' % (len(idx), len(man)))
    matched = mism = missing = 0
    mism_examples = []
    miss_examples = []
    for off, size, p in idx:
        if p not in man:
            missing += 1
            if len(miss_examples) < 8: miss_examples.append(p)
            continue
        moff, msize = man[p]
        if moff == off and msize == size:
            matched += 1
        else:
            mism += 1
            if len(mism_examples) < 8:
                mism_examples.append('%s idx=(0x%X,0x%X) man=(0x%X,0x%X)' % (p, off, size, moff, msize))
    print('matched=%d  mismatched=%d  missing_from_manifest=%d' % (matched, mism, missing))
    if mism_examples:
        print('MISMATCH examples:'); [print('  ', x) for x in mism_examples]
    if miss_examples:
        print('MISSING examples:'); [print('  ', x) for x in miss_examples]
    return mism == 0 and missing == 0

def emit(eu_manifest, outpath, usa_manifest=None):
    # Text-transform the committed port_asset_index.c: replace ONLY each entry's
    # ROM offset with the EU offset (keep size + path + every surrounding helper
    # untouched, so the file stays structurally identical and compiles the same).
    txt = open(INDEX, encoding='utf-8', errors='replace').read()
    man = parse_manifest(eu_manifest)
    stats = {'eu': 0, 'fallback': 0}

    def repl(m):
        off = int(m.group(1), 16); size = m.group(2); path = m.group(3)
        if path in man:
            eoff = man[path][0]; stats['eu'] += 1
        else:
            eoff = off; stats['fallback'] += 1   # variant-excluded -> keep USA
        return '{ 0x%08X, 0x%s, "%s" }' % (eoff, size, path)

    new = re.sub(r'\{\s*0x([0-9A-Fa-f]+)\s*,\s*0x([0-9A-Fa-f]+)\s*,\s*"([^"]+)"\s*\}', repl, txt)
    # The index embeds a ROM game-code check: USA BZME (42 5A 4D 45) -> EU BZMP
    # (42 5A 4D 50) so the EU ROM passes verification.
    new = new.replace('0x42, 0x5A, 0x4D, 0x45', '0x42, 0x5A, 0x4D, 0x50')
    new = new.replace('Generated by tools/generate_asset_index.py',
                      'Generated by tools/generate_asset_index.py (EU offsets — region-transformed)')
    open(outpath, 'w', encoding='utf-8').write(new)
    print('wrote %s: %d entries EU-mapped, %d kept USA (variant-excluded)' % (outpath, stats['eu'], stats['fallback']))

if __name__ == '__main__':
    cmd = sys.argv[1]
    if cmd == 'validate':
        sys.exit(0 if validate(sys.argv[2]) else 1)
    elif cmd == 'emit':
        emit(sys.argv[2], sys.argv[3], sys.argv[4] if len(sys.argv) > 4 else None)
    else:
        print(__doc__); sys.exit(1)
