#!/usr/bin/env python3
"""
generate_const_data.py — (re)generate port/data_const_stubs*.c from a baserom.

data_const_stubs.c holds ~400 raw ROM data blobs the decomp could not fully
decompile (gUnk_XXXX_data[N] @ ROM 0xOFFSET). The committed file is USA-only, so
the EU build links USA bytes for these symbols. This regenerates them per region:
the ROM offset of each blob is remapped to EU via the asset_processor manifests
(path-keyed), then the bytes are re-read from the EU ROM.

Usage:
    generate_const_data.py validate <usa_rom>
    generate_const_data.py emit <eu_rom> <out.c> <usa_manifest.csv> <eu_manifest.csv>
"""
import sys, re

SRC = 'port/data_const_stubs.c'
# match: /* SYMBOL @ ROM 0xOFFSET, N bytes */ \n const u8 SYMBOL[...]... = { BYTES };
BLOB_RE = re.compile(
    r'/\* (\w+) @ ROM 0x([0-9A-Fa-f]+), (\d+) bytes \*/\s*\n'
    r'(const u8 \w+\[\d+\][^=]*= \{)(.*?)(\};)', re.S)

def manifest(path):
    by_off = {}
    by_path = {}
    for line in open(path, encoding='utf-8', errors='replace'):
        if not line.strip():
            continue
        o, s, p = line.rstrip().split(',', 2)
        by_off[int(o)] = p
        by_path[p] = int(o)
    return by_off, by_path

def fmt_bytes(data):
    out = []
    for i in range(0, len(data), 16):
        out.append('    ' + ''.join('0x%02X,' % b for b in data[i:i+16]))
    return '\n' + '\n'.join(out) + '\n'

def validate(usa_rom_path):
    rom = open(usa_rom_path, 'rb').read()
    txt = open(SRC, encoding='utf-8', errors='replace').read()
    n = ok = bad = 0
    bad_ex = []
    for m in BLOB_RE.finditer(txt):
        sym, off, size = m.group(1), int(m.group(2), 16), int(m.group(3))
        n += 1
        committed = [int(x, 16) for x in re.findall(r'0x([0-9A-Fa-f]{2})', m.group(5))]
        fromrom = list(rom[off:off+size])
        if committed == fromrom:
            ok += 1
        else:
            bad += 1
            if len(bad_ex) < 8:
                bad_ex.append('%s @0x%X size=%d committed_len=%d rom_len=%d' %
                              (sym, off, size, len(committed), len(fromrom)))
    print('blobs=%d  reproduced=%d  mismatch=%d' % (n, ok, bad))
    for x in bad_ex:
        print('  XX', x)
    return bad == 0

def emit(eu_rom_path, outpath, usa_manifest, eu_manifest):
    eu = open(eu_rom_path, 'rb').read()
    usa_by_off, _ = manifest(usa_manifest)
    _, eu_by_path = manifest(eu_manifest)
    txt = open(SRC, encoding='utf-8', errors='replace').read()
    stats = {'eu': 0, 'same': 0, 'usa': 0}

    def repl(m):
        sym, usa_off, size = m.group(1), int(m.group(2), 16), int(m.group(3))
        path = usa_by_off.get(usa_off)
        head = m.group(4)
        if path is not None and path in eu_by_path:
            # Manifest knows the EU location of this blob -> re-read EU bytes.
            eu_off = eu_by_path[path]
            data = eu[eu_off:eu_off+size]
            if len(data) == size:
                stats['eu'] += 1
                return ('/* %s @ ROM 0x%06X, %d bytes (EU) */\n%s%s%s'
                        % (sym, eu_off, size, head, fmt_bytes(list(data)), m.group(6)))
        # Not in the manifest (or short read): keep the committed USA bytes. For
        # region-invariant engine data these are identical to EU; for the rest
        # this is the safest guess (no worse than the current USA-only file).
        stats['usa'] += 1
        return m.group(0)

    new = BLOB_RE.sub(repl, txt)
    new = new.replace('AUTO-GENERATED by tools/generate_const_data.py',
                      'AUTO-GENERATED by tools/generate_const_data.py (EU)')
    open(outpath, 'w', encoding='utf-8').write(new)
    print('wrote %s: %d EU-mapped, %d same-offset, %d USA-fallback'
          % (outpath, stats['eu'], stats['same'], stats['usa']))

if __name__ == '__main__':
    cmd = sys.argv[1]
    if cmd == 'validate':
        sys.exit(0 if validate(sys.argv[2]) else 1)
    elif cmd == 'emit':
        emit(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
    else:
        print(__doc__); sys.exit(1)
